In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:

dataset = pd.read_csv("/content/sample_data/Iris - Iris (1).csv")

In [3]:

dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
dataset.shape

(150, 6)

In [6]:
X = dataset.iloc[:,:4].values
X

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [7]:
y = dataset['Species'].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [8]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [9]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 1.46177627,  1.04033158,  0.14087022,  1.00964728],
       [-0.77754057, -0.97728118,  1.71861672, -1.1591161 ],
       [ 0.29546542, -0.47287799, -0.98609156,  0.30626456],
       [ 0.90194706,  0.78812999, -0.08452213,  0.95103205],
       [-0.9641503 , -0.47287799,  1.04243965, -1.51080746],
       [ 0.71533732,  1.04033158, -1.21148392,  1.12687773],
       [ 0.45874894,  0.40982759, -0.30991449,  0.24764933],
       [-1.22073869, -1.10338198, -0.08452213, -1.33496178],
       [ 0.83196841, -0.2206764 , -1.21148392,  0.65795592],
       [-0.91749787, -1.85998677, -0.08452213, -1.51080746],
       [ 1.648386  ,  0.40982759,  0.81704729,  0.89241682],
       [ 1.67171222,  0.0315252 , -0.08452213,  0.71657114],
       [ 0.73866354,  1.67083557,  1.26783201,  1.30272341],
       [-1.15076004, -0.85118039,  0.81704729, -1.45219224],
       [ 0.99525193,  1.29253318,  0.36626258,  1.0682625 ],
       [ 0.22548676,  0.53592839, -1.66226863,  0.30626456],
       [-0.31101623, -0.

In [10]:
X_test

array([[-1.5006533 , -1.98608757, -0.08452213, -1.62803791],
       [ 0.10885568, -0.0945756 , -0.7606992 ,  0.01318843],
       [ 0.64535867,  2.17523877, -0.08452213,  1.59579954],
       [ 1.06523058,  0.53592839, -0.7606992 ,  0.59934069],
       [-1.54730573, -1.35558358,  0.81704729, -1.33496178],
       [-1.29071734, -1.60778517,  1.26783201, -1.68665314],
       [-0.61425705,  0.66202919,  0.36626258,  0.36487978],
       [ 0.43542272, -0.2206764 , -0.30991449,  0.18903411],
       [ 0.59870624,  0.53592839, -0.30991449,  1.00964728],
       [-1.08078139, -0.59897879,  0.81704729, -1.39357701],
       [-0.89417165, -0.97728118,  0.81704729, -1.39357701],
       [-0.66090948, -1.10338198,  0.59165494, -1.45219224],
       [-1.6406106 , -1.10338198,  0.81704729, -1.39357701],
       [-1.73391547, -1.60778517,  0.14087022, -1.39357701],
       [-1.59395816, -1.22948278,  0.14087022, -1.39357701],
       [ 1.04190436,  2.30133956, -0.53530685,  1.65441477],
       [-0.24103758, -0.

In [11]:

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [12]:
y_pred = classifier.predict(X_test)
y_pred


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica'], dtype='<U15')

In [13]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[14,  0,  0],
       [ 0,  8,  0],
       [ 0,  0,  8]])

In [14]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  1.0


In [15]:



df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2    Iris-virginica   Iris-virginica
3    Iris-virginica   Iris-virginica
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7   Iris-versicolor  Iris-versicolor
8    Iris-virginica   Iris-virginica
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16  Iris-versicolor  Iris-versicolor
17      Iris-setosa      Iris-setosa
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22   Iris-virginica   Iris-virginica
23      Iris-setosa      Iris-setosa
24  Iris-versicolor  Iris-versicolor
25  Iris-versicolor  Iris-versicolor
26   Iris-virginica   Iris-virginica
27  Iris-versicolor  Iris-versicolor
28      Iris-setosa      Iris-setosa
29   Iris-virginica   Iris-virginica

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')


print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]
Accuracy: 1.00
Error Rate: 0.00
Precision: 1.00
Recall: 1.00
